local requestversion = version() 
local requiredVersion = "2.661.713" 
if requestversion == requiredVersion then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Zunes-Bypassed/UI/refs/heads/main/ReveliX.lua"))()
    return
end
local ReveliX =
{
	ReveliX_Outdated = Instance.new("ScreenGui"),
	Canvas = Instance.new("Frame"),
	copyLink = Instance.new("ImageButton"),
	Main = Instance.new("Frame"),
	TextLabel = Instance.new("TextLabel"),
	UIPadding = Instance.new("UIPadding"),
	Icon = Instance.new("ImageLabel"),
	UICorner = Instance.new("UICorner"),
	ImageLabel = Instance.new("ImageLabel"),
	Title = Instance.new("TextLabel"),
	UITextSizeConstraint = Instance.new("UITextSizeConstraint"),
	visit = Instance.new("TextLabel"),
	UITextSizeConstraint_1 = Instance.new("UITextSizeConstraint"),
	Changelog = Instance.new("Frame"),
	Title_1 = Instance.new("TextLabel"),
	UITextSizeConstraint_2 = Instance.new("UITextSizeConstraint"),
	UICorner_1 = Instance.new("UICorner"),
	ScrollingFrame = Instance.new("ScrollingFrame"),
	UIListLayout = Instance.new("UIListLayout"),
	UIPadding_1 = Instance.new("UIPadding"),
	item_template = Instance.new("Frame"),
	UICorner_2 = Instance.new("UICorner"),
	UIStroke = Instance.new("UIStroke"),
	Title_2 = Instance.new("TextLabel"),
	UIGradient = Instance.new("UIGradient"),
	Title_3 = Instance.new("TextLabel"),
	UITextSizeConstraint_3 = Instance.new("UITextSizeConstraint")
}
ReveliX.ReveliX_Outdated.IgnoreGuiInset = true
ReveliX.ReveliX_Outdated.Name = "ReveliX_Outdated"
ReveliX.ReveliX_Outdated.ScreenInsets = Enum.ScreenInsets.DeviceSafeInsets
ReveliX.ReveliX_Outdated.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
ReveliX.ReveliX_Outdated.Parent = gethui()
ReveliX.Canvas.BorderSizePixel = 0
ReveliX.Canvas.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
ReveliX.Canvas.AnchorPoint = Vector2.new(0.5, 0.5)
ReveliX.Canvas.Size = UDim2.new(1, 0, 1, 0)
ReveliX.Canvas.BorderColor3 = Color3.fromRGB(0, 0, 0)
ReveliX.Canvas.Name = "Canvas"
ReveliX.Canvas.Position = UDim2.new(0.5, 0, 0.5, 0)
ReveliX.Canvas.Parent = ReveliX.ReveliX_Outdated
ReveliX.copyLink = Instance.new("TextButton") 
ReveliX.copyLink.BorderSizePixel = 0
ReveliX.copyLink.Position = UDim2.new(0.5, 0, 0.9, 0)
ReveliX.copyLink.BackgroundColor3 = Color3.fromRGB(221, 221, 245)
ReveliX.copyLink.Name = "copyLink"
ReveliX.copyLink.AnchorPoint = Vector2.new(0.5, 0.5)
ReveliX.copyLink.Size = UDim2.new(0.190301, 0, 0.0700535, 0)
ReveliX.copyLink.BorderColor3 = Color3.fromRGB(0, 0, 0)
ReveliX.copyLink.BackgroundTransparency = 0.95
ReveliX.copyLink.Parent = ReveliX.Canvas
ReveliX.Main = Instance.new("Frame") 
ReveliX.Main.BorderSizePixel = 0
ReveliX.Main.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.Main.AnchorPoint = Vector2.new(0.5, 0.5)
ReveliX.Main.Size = UDim2.new(0.994505, 0, 0.913044, 0)
ReveliX.Main.BorderColor3 = Color3.fromRGB(0, 0, 0)
ReveliX.Main.BackgroundTransparency = 1
ReveliX.Main.Name = "Main"
ReveliX.Main.Position = UDim2.new(0.5, 0, 0.5, 0)
ReveliX.Main.Parent = ReveliX.copyLink
ReveliX.TextLabel = Instance.new("TextLabel") 
ReveliX.TextLabel.TextWrapped = true
ReveliX.TextLabel.BorderSizePixel = 0
ReveliX.TextLabel.TextScaled = true
ReveliX.TextLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.TextLabel.FontFace = Font.new("rbxasset://fonts/families/Ubuntu.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
ReveliX.TextLabel.Position = UDim2.new(0.5, 0, 0.5, 0)
ReveliX.TextLabel.AnchorPoint = Vector2.new(0.5, 0.5)
ReveliX.TextLabel.Size = UDim2.new(0.9, 0, 0.9, 0) 
ReveliX.TextLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.TextLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
ReveliX.TextLabel.Text = "Copy Link To Clipboard"
ReveliX.TextLabel.BackgroundTransparency = 1
ReveliX.TextLabel.TextXAlignment = Enum.TextXAlignment.Center 
ReveliX.TextLabel.TextYAlignment = Enum.TextYAlignment.Center 
ReveliX.TextLabel.Parent = ReveliX.Main
ReveliX.UICorner = Instance.new("UICorner") 
ReveliX.UICorner.CornerRadius = UDim.new(0.08, 0)
ReveliX.UICorner.Parent = ReveliX.copyLink
ReveliX.ImageLabel.BorderSizePixel = 0
ReveliX.ImageLabel.ScaleType = Enum.ScaleType.Fit
ReveliX.ImageLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.ImageLabel.Position = UDim2.new(0.51, 0, 0.05, 0)
ReveliX.ImageLabel.AnchorPoint = Vector2.new(0.51, 0.05)
ReveliX.ImageLabel.Image = "rbxassetid://128757719503511"
ReveliX.ImageLabel.Size = UDim2.new(0, 150, 0, 85) 
ReveliX.ImageLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
ReveliX.ImageLabel.BackgroundTransparency = 1
ReveliX.ImageLabel.Parent = ReveliX.Canvas
ReveliX.Title.TextWrapped = true
ReveliX.Title.TextScaled = true
ReveliX.Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.Title.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.ExtraBold, Enum.FontStyle.Normal)
ReveliX.Title.Position = UDim2.new(0.5, 0, 0.27104, 0)
ReveliX.Title.Name = "Title"
ReveliX.Title.AnchorPoint = Vector2.new(0.5, 0.25)
ReveliX.Title.TextSize = 14
ReveliX.Title.Size = UDim2.new(0.482036, 0, 0.0760031, 0)
ReveliX.Title.TextColor3 = Color3.fromRGB(240, 240, 240)
ReveliX.Title.BorderColor3 = Color3.fromRGB(27, 42, 53)
ReveliX.Title.Text = "New ReveliX Update Available!"
ReveliX.Title.BackgroundTransparency = 1
ReveliX.Title.Parent = ReveliX.Canvas
ReveliX.UITextSizeConstraint.MaxTextSize = 55
ReveliX.UITextSizeConstraint.Parent = ReveliX.Title
ReveliX.Changelog.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.Changelog.AnchorPoint = Vector2.new(0.5, 0.5)
ReveliX.Changelog.Size = UDim2.new(0.344172, 0, 0.314708, 0)
ReveliX.Changelog.BorderColor3 = Color3.fromRGB(27, 42, 53)
ReveliX.Changelog.Name = "Changelog"
ReveliX.Changelog.Position = UDim2.new(0.5, 0, 0.619537, 0)
ReveliX.Changelog.Parent = ReveliX.Canvas
ReveliX.Title_1.TextWrapped = true
ReveliX.Title_1.TextScaled = true
ReveliX.Title_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.Title_1.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.ExtraBold, Enum.FontStyle.Normal)
ReveliX.Title_1.Position = UDim2.new(0.0469997, 0, 0.0369999, 0)
ReveliX.Title_1.Name = "Title"
ReveliX.Title_1.TextSize = 14
ReveliX.Title_1.Size = UDim2.new(0.893926, 0, 0.147619, 0)
ReveliX.Title_1.TextColor3 = Color3.fromRGB(240, 240, 240)
ReveliX.Title_1.BorderColor3 = Color3.fromRGB(27, 42, 53)
ReveliX.Title_1.Text = "Changelog:"
ReveliX.Title_1.BackgroundTransparency = 1
ReveliX.Title_1.TextXAlignment = Enum.TextXAlignment.Left
ReveliX.Title_1.Parent = ReveliX.Changelog
ReveliX.UITextSizeConstraint_2.MaxTextSize = 26
ReveliX.UITextSizeConstraint_2.Parent = ReveliX.Title_1
ReveliX.UICorner_1.CornerRadius = UDim.new(0, 10)
ReveliX.UICorner_1.Parent = ReveliX.Changelog
ReveliX.ScrollingFrame.ScrollingDirection = Enum.ScrollingDirection.Y
ReveliX.ScrollingFrame.BorderSizePixel = 0
ReveliX.ScrollingFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.ScrollingFrame.BackgroundTransparency = 1
ReveliX.ScrollingFrame.Size = UDim2.new(0.949102, 0, 0.761723, 0)
ReveliX.ScrollingFrame.Active = true
ReveliX.ScrollingFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
ReveliX.ScrollingFrame.ScrollBarImageTransparency = 0.83
ReveliX.ScrollingFrame.ScrollBarThickness = 0
ReveliX.ScrollingFrame.Position = UDim2.new(0.0329341, 0, 0.210847, 0)
ReveliX.ScrollingFrame.Parent = ReveliX.Changelog
ReveliX.UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
ReveliX.UIListLayout.Padding = UDim.new(0.01, 0)
ReveliX.UIListLayout.Parent = ReveliX.ScrollingFrame
ReveliX.UIPadding_1.PaddingTop = UDim.new(0.005, 0)
ReveliX.UIPadding_1.PaddingLeft = UDim.new(0.01, 0)
ReveliX.UIPadding_1.Parent = ReveliX.ScrollingFrame
ReveliX.item_template.Active = true
ReveliX.item_template.BorderSizePixel = 0
ReveliX.item_template.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.item_template.Size = UDim2.new(0.956247, 0, 0.0593393, 0)
ReveliX.item_template.LayoutOrder = 1
ReveliX.item_template.BorderColor3 = Color3.fromRGB(47, 48, 53)
ReveliX.item_template.BackgroundTransparency = 0.95
ReveliX.item_template.Name = "item_template"
ReveliX.item_template.Position = UDim2.new(-4.30065e-08, 0, 0.00816908, 0)
ReveliX.item_template.ZIndex = 150
ReveliX.item_template.Parent = ReveliX.ScrollingFrame
ReveliX.UICorner_2.CornerRadius = UDim.new(0.12, 0)
ReveliX.UICorner_2.Parent = ReveliX.item_template
ReveliX.UIStroke.Color = Color3.fromRGB(211, 211, 211)
ReveliX.UIStroke.Thickness = 1.2
ReveliX.UIStroke.Transparency = 0.86
ReveliX.UIStroke.Parent = ReveliX.item_template
ReveliX.Title_2.TextWrapped = true
ReveliX.Title_2.Active = true
ReveliX.Title_2.BorderSizePixel = 0
ReveliX.Title_2.TextScaled = true
ReveliX.Title_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.Title_2.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Bold, Enum.FontStyle.Normal)
ReveliX.Title_2.Position = UDim2.new(0.5, 0, 0.5, 0)
ReveliX.Title_2.Name = "Title"
ReveliX.Title_2.AnchorPoint = Vector2.new(0.5, 0.5)
ReveliX.Title_2.TextSize = 16
ReveliX.Title_2.Size = UDim2.new(0.959219, 0, 0.661736, 0)
ReveliX.Title_2.ZIndex = 151
ReveliX.Title_2.TextColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.Title_2.BorderColor3 = Color3.fromRGB(27, 42, 53)
ReveliX.Title_2.Text = "+ Infinite Yield"
ReveliX.Title_2.BackgroundTransparency = 1
ReveliX.Title_2.TextXAlignment = Enum.TextXAlignment.Left
ReveliX.Title_2.Selectable = true
ReveliX.Title_2.Parent = ReveliX.item_template
ReveliX.UIGradient.Offset = Vector2.new(0, -0.45)
ReveliX.UIGradient.Transparency = NumberSequence.new{ NumberSequenceKeypoint.new(0, 0.65625), NumberSequenceKeypoint.new(1, 0) }
ReveliX.UIGradient.Color = ColorSequence.new{ ColorSequenceKeypoint.new(0, Color3.fromRGB(34, 35, 39)), ColorSequenceKeypoint.new(1, Color3.fromRGB(53, 54, 61)) }
ReveliX.UIGradient.Rotation = -80
ReveliX.UIGradient.Parent = ReveliX.Changelog
ReveliX.Title_3.TextWrapped = true
ReveliX.Title_3.TextScaled = true
ReveliX.Title_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ReveliX.Title_3.FontFace = Font.new("rbxassetid://12187365364", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
ReveliX.Title_3.Position = UDim2.new(0.5, 0, 0.358405, 0)
ReveliX.Title_3.Name = "Title"
ReveliX.Title_3.AnchorPoint = Vector2.new(0.5, 0.25)
ReveliX.Title_3.TextSize = 14
ReveliX.Title_3.Size = UDim2.new(0.482036, 0, 0.12145, 0)
ReveliX.Title_3.TextColor3 = Color3.fromRGB(240, 240, 240)
ReveliX.Title_3.BorderColor3 = Color3.fromRGB(27, 42, 53)
ReveliX.Title_3.Text = "Please download ReveliX again from the official website or contact us on Discord if you encounter any issues!"
ReveliX.Title_3.BackgroundTransparency = 1
ReveliX.Title_3.Parent = ReveliX.Canvas
ReveliX.UITextSizeConstraint_3.MaxTextSize = 28
ReveliX.UITextSizeConstraint_3.Parent = ReveliX.Title_3
ReveliX.copyLink.Activated:Connect(function()
	setclipboard("https://discord.gg/5FDxfZXM8x")
end)
ReveliX.item_template.Visible = false
local function changelog(text)
	local newItem = ReveliX.item_template:Clone()
	newItem.Name = "Changelog"
	newItem.Title.Text = text
	newItem.Parent = ReveliX.ScrollingFrame
	newItem.Visible = true
end
changelog("Optimize Performance")  
changelog("Fix UI Bugs")  
changelog("Improve Loading Speed")  
changelog("Fix Script Execution Issues")  
changelog("Update Compatibility with New Roblox Version")  
changelog("Improve Stability")
